export const user_fields = [
    {
        block_name:"Basic Information",
        fields:[
            {
                label:"Name",
                name:"name",
                type:"text",
                default:"",
                required:true,
                readonly:false
            },
            {
                label:"Email",
                name:"email",
                type:"text",
                default:"",
                required:true,
                readonly:false
            },
            {
                label:"Password",
                name:"password",
                type:"text",
                default:"",
                required:true,
                readonly:false
            },
        ]
    },
    {
        block_name:"Module Privileges",
        fields:[
            {
                label:"Incident",
                name:"incident",
                type:"checkbox",
                default:true,
                required:false,
                readonly:false
            },
            {
                label:"Resources",
                name:"resources",
                type:"checkbox",
                default:true,
                required:false,
                readonly:false
            },
            {
                label:"Pre Plan",
                name:"preplan",
                type:"checkbox",
                default:true,
                required:false,
                readonly:false
            },
            {
                label:"Contact",
                name:"contact",
                type:"checkbox",
                default:true,
                required:false,
                readonly:false
            },
            {
                label:"Agency",
                name:"agency",
                type:"checkbox",
                default:true,
                required:false,
                readonly:false
            },
            {
                label:"Responder",
                name:"responder",
                type:"checkbox",
                default:true,
                required:false,
                readonly:false
            },
            {
                label:"Incident Map",
                name:"incident_map",
                type:"checkbox",
                default:true,
                required:false,
                readonly:false
            },
            {
                label:"User",
                name:"user",
                type:"checkbox",
                default:true,
                required:false,
                readonly:false
            },
        ]
    },
];